import { Bot } from './types';

export const BOTS: Bot[] = [
    {
        id: 'g-interviewer',
        name: 'Gloria',
        description: 'A friendly guide who helps you create your first Life Context file through a simple conversation.',
        description_de: 'Ein freundlicher Guide, der Ihnen hilft, Ihre erste Lebenskontext-Datei durch ein einfaches Gespräch zu erstellen.',
        avatar: 'https://api.dicebear.com/8.x/micah/svg?seed=Erik&backgroundColor=d1d4f9&hairColor=86efac',
        style: 'Conversational, Structured, Helpful',
        style_de: 'Gesprächsorientiert, Strukturiert, Hilfsbereit',
        accessTier: 'guest',
    },
    {
        id: 'max-ambitious',
        name: 'Max',
        description: 'A performance coach who helps you think bigger by asking the right questions to unlock your potential.',
        description_de: 'Ein Leistungscoach, der Ihnen hilft, größer zu denken, indem er die richtigen Fragen stellt, um Ihr Potenzial freizusetzen.',
        avatar: 'https://api.dicebear.com/8.x/micah/svg?seed=Elara&backgroundColor=d1d4f9,c0aede,b6e3f4&radius=50&mouth=smile&shirtColor=ffffff',
        style: 'Motivational, Inquisitive, Reflective',
        style_de: 'Motivierend, Neugierig, Reflektierend',
        accessTier: 'guest',
    },
    {
        id: 'ava-strategic',
        name: 'Ava',
        description: 'A coach specializing in strategic thinking and business decision-making to help you see the bigger picture.',
        description_de: 'Eine Beraterin, die auf strategisches Denken und Geschäftsentscheidungen spezialisiert ist, um Ihnen zu helfen, das große Ganze zu sehen.',
        avatar: 'https://api.dicebear.com/8.x/micah/svg?seed=Sophie&backgroundColor=d1d4f9,c0aede,b6e3f4&radius=50&mouth=smirk,smile&shirtColor=ffffff&hair=full&hairColor=cb682f',
        style: 'Strategic, Long-term, Analytical',
        style_de: 'Strategisch, Langfristig, Analytisch',
        accessTier: 'guest',
    },
    {
        id: 'kenji-stoic',
        name: 'Kenji',
        description: 'A coach grounded in Stoic philosophy, helping you build resilience.',
        description_de: 'Ein Coach, der auf der stoischen Philosophie basiert und Ihnen hilft, Widerstandsfähigkeit aufzubauen.',
        avatar: 'https://api.dicebear.com/9.x/micah/svg?seed=Kimberly&baseColor=f9c9b6&backgroundColor=ffdfbf&mouth=smirk',
        style: 'Composed, Philosophical, Wise',
        style_de: 'Besonnen, Philosophisch, Weise',
        accessTier: 'guest',
    },
    {
        id: 'chloe-cbt',
        name: 'Chloe',
        description: 'A professional coach using cognitive-behavioral coaching techniques to help you modify unhelpful thought patterns and apply new behavioral strategies.',
        description_de: 'Eine professionelle Beraterin, die kognitiv-verhaltensorientierte Coaching-Techniken anwendet, um Ihnen zu helfen, hinderliche Gedankenmuster zu verändern, und damit neue Verhaltensstrategien anzuwenden.',
        avatar: 'https://api.dicebear.com/8.x/micah/svg?seed=Chloe&backgroundColor=d1d4f9,c0aede,b6e3f4&radius=50&mouth=smile,smirk&shirtColor=ffffff',
        style: 'Cognitive-Behavioral, Structured, Evidence-Based',
        style_de: 'Kognitiv-Verhaltensorientiert, Strukturiert, Evidenzbasiert',
        accessTier: 'registered',
    },
    {
        id: 'rob-pq',
        name: 'Rob',
        description: 'An experienced coach specialized in Positive Intelligence to help you build mental fitness.',
        description_de: 'Ein erfahrener Coach, spezialisiert auf Positive Intelligenz, der Ihnen hilft, mentale Fitness aufzubauen.',
        avatar: 'https://api.dicebear.com/8.x/micah/svg?seed=Rob&backgroundColor=d1d4f9,c0aede,b6e3f4&radius=50&mouth=smile&shirtColor=ffffff',
        style: 'Positive Intelligence, Empathetic, Mindful',
        style_de: 'Positive Intelligence, Empathisch, Achtsam',
        accessTier: 'premium',
    },
    {
        id: 'nexus-gps',
        name: 'Nobody',
        description: 'A life and career coach using the GPS (Goals, Present, Strategy) framework to help you find your own solutions.',
        description_de: 'Ein Lebens- und Karrierecoach, der das GPS-Framework (Ziele, Gegenwart, Strategie) verwendet, um Ihnen zu helfen, Ihre eigenen Lösungen zu finden.',
        avatar: 'https://api.dicebear.com/8.x/micah/svg?seed=Alex&backgroundColor=d1d4f9,c0aede,b6e3f4&radius=50&mouth=smirk&shirtColor=ffffff',
        style: 'GPS Framework, Inquisitive, Empowering',
        style_de: 'GPS-Framework, Neugierig, Befähigend',
        accessTier: 'premium',
    }
];