import { Bot } from './types';

export const BOTS: Bot[] = [
    {
        id: 'g-interviewer',
        name: 'Gloria',
        description: 'A friendly guide who helps you create your first Life Context file through a simple conversation.',
        description_de: 'Ein freundlicher Guide, der Ihnen hilft, Ihre erste Lebenskontext-Datei durch ein einfaches Gespräch zu erstellen.',
        avatar: 'https://api.dicebear.com/8.x/micah/svg?seed=Erik&backgroundColor=d1d4f9&hairColor=86efac',
        style: 'Conversational, Structured, Helpful',
        style_de: 'Gesprächsorientiert, Strukturiert, Hilfsbereit',
        accessTier: 'guest',
    },
    {
        id: 'max-ambitious',
        name: 'Max',
        description: 'A performance coach who helps you think bigger by asking the right questions to unlock your potential.',
        description_de: 'Ein Leistungscoach, der Ihnen hilft, größer zu denken, indem er die richtigen Fragen stellt, um Ihr Potenzial freizusetzen.',
        avatar: 'https://api.dicebear.com/8.x/micah/svg?seed=Elara&backgroundColor=B8D4B8&radius=50&mouth=smile&shirtColor=ffffff',
        style: 'Motivational, Inquisitive, Reflective',
        style_de: 'Motivierend, Neugierig, Reflektierend',
        accessTier: 'guest',
    },
    {
        id: 'ava-strategic',
        name: 'Ava',
        description: 'A coach specializing in strategic thinking and business decision-making to help you see the bigger picture.',
        description_de: 'Eine Beraterin, die auf strategisches Denken und Geschäftsentscheidungen spezialisiert ist, um Ihnen zu helfen, das große Ganze zu sehen.',
        avatar: 'https://api.dicebear.com/8.x/micah/svg?seed=Sophie&backgroundColor=d1d4f9,c0aede,b6e3f4&radius=50&mouth=smirk,smile&shirtColor=ffffff&hair=full&hairColor=cb682f',
        style: 'Strategic, Long-term, Analytical',
        style_de: 'Strategisch, Langfristig, Analytisch',
        accessTier: 'guest',
    },
    {
        id: 'kenji-stoic',
        name: 'Kenji',
        description: 'A coach grounded in Stoic philosophy, helping you build resilience for challenges.',
        description_de: 'Ein Coach, der auf der stoischen Philosophie basiert und Ihnen hilft, Widerstandsfähigkeit für Herausforderungen aufzubauen.',
        avatar: 'https://api.dicebear.com/9.x/micah/svg?seed=Kimberly&baseColor=f9c9b6&backgroundColor=FBE870&mouth=smirk',
        style: 'Composed, Philosophical, Wise',
        style_de: 'Besonnen, Philosophisch, Weise',
        accessTier: 'premium',
    },
    {
        id: 'chloe-cbt',
        name: 'Chloe',
        description: 'A professional coach using structured reflection techniques to help you recognize unhelpful thought patterns and develop new behavioral strategies.',
        description_de: 'Eine professionelle Beraterin, die strukturierte Reflexionsmethoden anwendet, um Ihnen zu helfen, hinderliche Gedankenmuster zu erkennen und neue Verhaltensstrategien zu entwickeln.',
        avatar: 'https://api.dicebear.com/8.x/micah/svg?seed=Chloe&backgroundColor=ffdfbf&radius=50&mouth=smile,smirk&shirtColor=ffffff',
        style: 'Reflective, Structured, Evidence-Based',
        style_de: 'Reflektierend, Strukturiert, Evidenzbasiert',
        accessTier: 'premium',
        experimentalMode: 'DPFL', // 🧪 Enable DPFL learning loop
    },
    {
        id: 'rob-pq',
        name: 'Rob',
        description: 'An experienced coach helping you build mental fitness and resilience by recognizing self-sabotaging patterns.',
        description_de: 'Ein erfahrener Coach, der Ihnen hilft, mentale Fitness und Resilienz aufzubauen, indem Sie selbstsabotierende Muster erkennen.',
        avatar: 'https://api.dicebear.com/8.x/micah/svg?seed=Rob&backgroundColor=E8E8E8&radius=50&mouth=smile&shirtColor=ffffff',
        style: 'Mental Fitness, Empathetic, Mindful',
        style_de: 'Mentale Fitness, Empathisch, Achtsam',
        accessTier: 'premium',
    },
    {
        id: 'nexus-gps',
        name: 'Nobody',
        description: 'A life and career coach using the GPS (Goals, Present, Strategy) framework to help you find your own solutions.',
        description_de: 'Ein Lebens- und Karrierecoach, der das GPS-Framework (Ziele, Gegenwart, Strategie) verwendet, um Ihnen zu helfen, Ihre eigenen Lösungen zu finden.',
        avatar: 'https://api.dicebear.com/8.x/micah/svg?seed=Alex&backgroundColor=d1d4f9,c0aede,b6e3f4&radius=50&mouth=smirk&shirtColor=ffffff',
        style: 'GPS Framework, Inquisitive, Empowering',
        style_de: 'GPS-Framework, Neugierig, Befähigend',
        accessTier: 'guest',
    },
    {
        id: 'victor-bowen',
        name: 'Victor',
        description: 'A systemic coach inspired by family systems theory concepts, helping you recognize patterns and develop differentiated responses.',
        description_de: 'Ein systemischer Coach, inspiriert von Konzepten der Familientheorie, der Ihnen hilft, Muster zu erkennen und differenzierte Reaktionen zu entwickeln.',
        avatar: 'https://api.dicebear.com/8.x/micah/svg?seed=VictorCoSerious&backgroundColor=ff9999&radius=50&mouth=smirk&shirtColor=ffffff',
        style: 'Systemic, Analytical, Neutral',
        style_de: 'Systemisch, Analytisch, Neutral',
        accessTier: 'premium',
    }
];