import { Bot } from './types';

export const BOTS: Bot[] = [
    {
        id: 'max-ambitious',
        name: 'Max',
        description: 'A performance coach who helps you think bigger by asking the right questions to unlock your potential.',
        description_de: 'Ein Leistungscoach, der Ihnen hilft, größer zu denken, indem er die richtigen Fragen stellt, um Ihr Potenzial freizusetzen.',
        avatar: 'https://api.dicebear.com/8.x/micah/svg?seed=Elara&backgroundColor=d1d4f9,c0aede,b6e3f4&radius=50&mouth=pucker,smile&shirtColor=ffffff',
        style: 'Motivational, Inquisitive, Reflective',
        style_de: 'Motivierend, Neugierig, Reflektierend',
        accessTier: 'guest',
    },
    {
        id: 'ava-strategic',
        name: 'Ava',
        description: 'A coach specializing in strategic thinking and business decision-making to help you see the bigger picture.',
        description_de: 'Eine Beraterin, die auf strategisches Denken und Geschäftsentscheidungen spezialisiert ist, um Ihnen zu helfen, das große Ganze zu sehen.',
        avatar: 'https://api.dicebear.com/8.x/micah/svg?seed=Ava&backgroundColor=d1d4f9,c0aede,b6e3f4&radius=50&mouth=pucker,smile&shirtColor=ffffff',
        style: 'Strategic, Long-term, Analytical',
        style_de: 'Strategisch, Langfristig, Analytisch',
        accessTier: 'guest',
    },
    {
        id: 'kenji-stoic',
        name: 'Kenji',
        description: 'A coach grounded in Stoic philosophy, helping you build resilience and focus on what you control.',
        description_de: 'Ein Coach, der auf der stoischen Philosophie basiert und Ihnen hilft, Widerstandsfähigkeit aufzubauen und sich auf den eigenen Einflussbereich zu fokussieren.',
        avatar: 'https://api.dicebear.com/8.x/micah/svg?seed=Kenji&backgroundColor=d1d4f9,c0aede,b6e3f4&radius=50&mouth=pucker,smile&shirtColor=ffffff',
        style: 'Resilient, Stoic, Wise',
        style_de: 'Belastbar, Stoisch, Weise',
        accessTier: 'guest',
    },
    {
        id: 'chloe-cbt',
        name: 'Chloe',
        description: 'A professional coach using Cognitive Behavioral Therapy (CBT) to help you modify unhelpful thought patterns.',
        description_de: 'Eine professionelle Beraterin, die Kognitive Verhaltenstherapie (KVT) anwendet, um Ihnen zu helfen, hinderliche Gedankenmuster zu verändern.',
        avatar: 'https://api.dicebear.com/8.x/micah/svg?seed=Chloe&backgroundColor=d1d4f9,c0aede,b6e3f4&radius=50&mouth=pucker,smile&shirtColor=ffffff',
        style: 'CBT, Structured, Evidence-Based',
        style_de: 'KVT, Strukturiert, Evidenzbasiert',
        accessTier: 'registered',
    },
    {
        id: 'rob-pq',
        name: 'Rob',
        description: 'An experienced coach specialized in Positive Intelligence to help you build mental fitness.',
        description_de: 'Ein erfahrener Coach, spezialisiert auf Positive Intelligenz, der Ihnen hilft, mentale Fitness aufzubauen.',
        avatar: 'https://api.dicebear.com/8.x/micah/svg?seed=Rob&backgroundColor=d1d4f9,c0aede,b6e3f4&radius=50&mouth=pucker,smile&shirtColor=ffffff',
        style: 'Positive Intelligence, Empathetic, Mindful',
        style_de: 'Positive Intelligence, Empathisch, Achtsam',
        accessTier: 'premium',
    },
    {
        id: 'nexus-gps',
        name: 'Nobody',
        description: 'A life and career coach using the GPS (Goals, Present, Strategy) framework to help you find your own solutions.',
        description_de: 'Ein Lebens- und Karrierecoach, der das GPS-Framework (Ziele, Gegenwart, Strategie) verwendet, um Ihnen zu helfen, Ihre eigenen Lösungen zu finden.',
        avatar: 'https://api.dicebear.com/8.x/micah/svg?seed=Nobody&backgroundColor=d1d4f9,c0aede,b6e3f4&radius=50&mouth=pucker,smile&shirtColor=ffffff',
        style: 'GPS Framework, Inquisitive, Empowering',
        style_de: 'GPS-Framework, Neugierig, Befähigend',
        accessTier: 'premium',
    }
];