export const brand = {
  appName: 'Meaningful Conversations',
  appNameDe: 'Sinnstiftende Gespräche',
  shortName: 'Meaningful',
  providerName: 'manualmode.at',
  providerUrl: 'https://www.manualmode.at',
  contactEmail: 'test@example.com',
  ownerName: 'Test User',
  primaryColor: '#1B7272',
  primaryColorDark: '#165a5a',
  domainStaging: 'mc-beta.manualmode.at',
  domainProduction: 'mc-app.manualmode.at',
  appUrlProduction: 'https://mc-app.manualmode.at',
  serverIp: '',
  color1: '#5BBFBF',
  color2: '#3D9E9E',
  color3: '#1B7272',
  color4: '#165a5a',
  accent: '#F59E0B',
  loader: 'steering-wheel' as const,
} as const;
