import React from 'react';
import { ArrowLeftIcon } from './icons/ArrowLeftIcon';

interface InfoViewProps {
    onBack: () => void;
}

const DisclaimerView: React.FC<InfoViewProps> = ({ onBack }) => {
    return (
        <div className="w-full max-w-3xl mx-auto p-8 space-y-6 bg-transparent border border-gray-700 my-10 animate-fadeIn">
            <div className="relative text-center">
                <button onClick={onBack} className="absolute left-0 top-1 p-2 rounded-full hover:bg-gray-800 transition-colors">
                    <ArrowLeftIcon className="w-6 h-6 text-gray-400"/>
                </button>
                <h1 className="text-3xl font-bold text-gray-200 uppercase">Disclaimer</h1>
            </div>
            <div className="prose prose-invert max-w-none text-gray-300 space-y-4 leading-relaxed">
                <p>The advice and insights provided by the AI coaches in Meaningful Conversations are for informational and self-reflection purposes only. They are generated by an AI model and do not constitute professional advice.</p>
                <h2 className="text-xl font-semibold text-gray-200">Not a Substitute for Professional Help</h2>
                <p>This application is not a substitute for professional medical advice, diagnosis, treatment, therapy, or financial or legal counsel. Always seek the advice of a qualified professional with any questions you may have regarding a medical condition, mental health, or other professional matters.</p>
                <h2 className="text-xl font-semibold text-gray-200">No Guarantees</h2>
                <p>We make no guarantees about the accuracy, reliability, or completeness of the information provided by the AI coaches. Your reliance on any information provided by this application is solely at your own risk.</p>
            </div>
        </div>
    );
};

export default DisclaimerView;