import { Bot, Message } from '../types';
import { BOTS } from '../constants';

export interface TestScenario {
    id: string;
    name: string;
    description: string;
    bot: Bot;
    chatHistory: Message[];
}

const simpleBot = BOTS.find(b => b.id === 'max-ambitious')!;
const cbtBot = BOTS.find(b => b.id === 'chloe-cbt')!;
const interviewBot = BOTS.find(b => b.id === 'g-interviewer')!;
const chloeBot = BOTS.find(b => b.id === 'chloe-cbt')!;

export const getTestScenarios = (t: (key: string) => string): TestScenario[] => [
    {
        id: 'interview_formatting',
        name: t('scenario_interview_name'),
        description: t('scenario_interview_desc'),
        bot: interviewBot,
        chatHistory: [ 
             { id: '1', role: 'bot', text: t('scenario_interview_chathistory_bot'), timestamp: new Date().toISOString() },
             { id: '2', role: 'user', text: t('scenario_interview_chathistory_user'), timestamp: new Date().toISOString() },
             { id: '3', role: 'bot', text: t('scenario_interview_chathistory_bot2'), timestamp: new Date().toISOString() },
             { id: '4', role: 'user', text: t('scenario_interview_chathistory_user2'), timestamp: new Date().toISOString() },
        ],
    },
    {
        id: 'simple_update',
        name: t('scenario_simple_update_name'),
        description: t('scenario_simple_update_desc'),
        bot: simpleBot,
        chatHistory: [
            { id: '1', role: 'user', text: t('scenario_simple_update_user'), timestamp: new Date().toISOString() },
            { id: '2', role: 'bot', text: t('scenario_simple_update_bot'), timestamp: new Date().toISOString() },
            { id: '3', role: 'user', text: t('scenario_simple_update_user2'), timestamp: new Date().toISOString() },
        ],
    },
    {
        id: 'complex_update',
        name: t('scenario_complex_update_name'),
        description: t('scenario_complex_update_desc'),
        bot: cbtBot,
        chatHistory: [
            { id: '1', role: 'user', text: t('scenario_complex_update_user1'), timestamp: new Date().toISOString() },
            { id: '2', role: 'bot', text: t('scenario_complex_update_bot1'), timestamp: new Date().toISOString() },
            { id: '3', role: 'user', text: t('scenario_complex_update_user2'), timestamp: new Date().toISOString() },
            { id: '4', role: 'bot', text: t('scenario_complex_update_bot2'), timestamp: new Date().toISOString() },
            { id: '5', role: 'user', text: t('scenario_complex_update_user3'), timestamp: new Date().toISOString() },
        ],
    },
    {
        id: 'next_steps',
        name: t('scenario_next_steps_name'),
        description: t('scenario_next_steps_desc'),
        bot: simpleBot,
        chatHistory: [
            { id: '1', role: 'user', text: t('scenario_next_steps_user1'), timestamp: new Date().toISOString() },
            { id: '2', role: 'bot', text: t('scenario_next_steps_bot1'), timestamp: new Date().toISOString() },
            { id: '3', role: 'user', text: t('scenario_next_steps_user2'), timestamp: new Date().toISOString() },
        ],
    },
    // ============================================
    // DPC/DPFL Extended Test Scenarios (12-14 messages each)
    // ============================================
    {
        id: 'dpc_riemann',
        name: '🧪 ' + t('scenario_dpc_riemann_name'),
        description: t('scenario_dpc_riemann_desc'),
        bot: chloeBot,
        chatHistory: [
            { id: '1', role: 'user', text: t('scenario_dpc_riemann_user1'), timestamp: new Date().toISOString() },
            { id: '2', role: 'bot', text: t('scenario_dpc_riemann_bot1'), timestamp: new Date().toISOString() },
            { id: '3', role: 'user', text: t('scenario_dpc_riemann_user2'), timestamp: new Date().toISOString() },
            { id: '4', role: 'bot', text: t('scenario_dpc_riemann_bot2'), timestamp: new Date().toISOString() },
            { id: '5', role: 'user', text: t('scenario_dpc_riemann_user3'), timestamp: new Date().toISOString() },
            { id: '6', role: 'bot', text: t('scenario_dpc_riemann_bot3'), timestamp: new Date().toISOString() },
            { id: '7', role: 'user', text: t('scenario_dpc_riemann_user4'), timestamp: new Date().toISOString() },
            { id: '8', role: 'bot', text: t('scenario_dpc_riemann_bot4'), timestamp: new Date().toISOString() },
            { id: '9', role: 'user', text: t('scenario_dpc_riemann_user5'), timestamp: new Date().toISOString() },
            { id: '10', role: 'bot', text: t('scenario_dpc_riemann_bot5'), timestamp: new Date().toISOString() },
            { id: '11', role: 'user', text: t('scenario_dpc_riemann_user6'), timestamp: new Date().toISOString() },
            { id: '12', role: 'bot', text: t('scenario_dpc_riemann_bot6'), timestamp: new Date().toISOString() },
            { id: '13', role: 'user', text: t('scenario_dpc_riemann_user7'), timestamp: new Date().toISOString() },
            { id: '14', role: 'bot', text: t('scenario_dpc_riemann_bot7'), timestamp: new Date().toISOString() },
            { id: '15', role: 'user', text: t('scenario_dpc_riemann_user8'), timestamp: new Date().toISOString() },
            { id: '16', role: 'bot', text: t('scenario_dpc_riemann_bot8'), timestamp: new Date().toISOString() },
            { id: '17', role: 'user', text: t('scenario_dpc_riemann_user9'), timestamp: new Date().toISOString() },
            { id: '18', role: 'bot', text: t('scenario_dpc_riemann_bot9'), timestamp: new Date().toISOString() },
            { id: '19', role: 'user', text: t('scenario_dpc_riemann_user10'), timestamp: new Date().toISOString() },
            { id: '20', role: 'bot', text: t('scenario_dpc_riemann_bot10'), timestamp: new Date().toISOString() },
        ],
    },
    {
        id: 'dpc_ocean',
        name: '🧪 ' + t('scenario_dpc_ocean_name'),
        description: t('scenario_dpc_ocean_desc'),
        bot: chloeBot,
        chatHistory: [
            { id: '1', role: 'user', text: t('scenario_dpc_ocean_user1'), timestamp: new Date().toISOString() },
            { id: '2', role: 'bot', text: t('scenario_dpc_ocean_bot1'), timestamp: new Date().toISOString() },
            { id: '3', role: 'user', text: t('scenario_dpc_ocean_user2'), timestamp: new Date().toISOString() },
            { id: '4', role: 'bot', text: t('scenario_dpc_ocean_bot2'), timestamp: new Date().toISOString() },
            { id: '5', role: 'user', text: t('scenario_dpc_ocean_user3'), timestamp: new Date().toISOString() },
            { id: '6', role: 'bot', text: t('scenario_dpc_ocean_bot3'), timestamp: new Date().toISOString() },
            { id: '7', role: 'user', text: t('scenario_dpc_ocean_user4'), timestamp: new Date().toISOString() },
            { id: '8', role: 'bot', text: t('scenario_dpc_ocean_bot4'), timestamp: new Date().toISOString() },
            { id: '9', role: 'user', text: t('scenario_dpc_ocean_user5'), timestamp: new Date().toISOString() },
            { id: '10', role: 'bot', text: t('scenario_dpc_ocean_bot5'), timestamp: new Date().toISOString() },
            { id: '11', role: 'user', text: t('scenario_dpc_ocean_user6'), timestamp: new Date().toISOString() },
            { id: '12', role: 'bot', text: t('scenario_dpc_ocean_bot6'), timestamp: new Date().toISOString() },
            { id: '13', role: 'user', text: t('scenario_dpc_ocean_user7'), timestamp: new Date().toISOString() },
            { id: '14', role: 'bot', text: t('scenario_dpc_ocean_bot7'), timestamp: new Date().toISOString() },
            { id: '15', role: 'user', text: t('scenario_dpc_ocean_user8'), timestamp: new Date().toISOString() },
            { id: '16', role: 'bot', text: t('scenario_dpc_ocean_bot8'), timestamp: new Date().toISOString() },
            { id: '17', role: 'user', text: t('scenario_dpc_ocean_user9'), timestamp: new Date().toISOString() },
            { id: '18', role: 'bot', text: t('scenario_dpc_ocean_bot9'), timestamp: new Date().toISOString() },
            { id: '19', role: 'user', text: t('scenario_dpc_ocean_user10'), timestamp: new Date().toISOString() },
            { id: '20', role: 'bot', text: t('scenario_dpc_ocean_bot10'), timestamp: new Date().toISOString() },
        ],
    },
    {
        id: 'dpfl_riemann',
        name: '📊 ' + t('scenario_dpfl_riemann_name'),
        description: t('scenario_dpfl_riemann_desc'),
        bot: chloeBot,
        chatHistory: [
            { id: '1', role: 'user', text: t('scenario_dpfl_riemann_user1'), timestamp: new Date().toISOString() },
            { id: '2', role: 'bot', text: t('scenario_dpfl_riemann_bot1'), timestamp: new Date().toISOString() },
            { id: '3', role: 'user', text: t('scenario_dpfl_riemann_user2'), timestamp: new Date().toISOString() },
            { id: '4', role: 'bot', text: t('scenario_dpfl_riemann_bot2'), timestamp: new Date().toISOString() },
            { id: '5', role: 'user', text: t('scenario_dpfl_riemann_user3'), timestamp: new Date().toISOString() },
            { id: '6', role: 'bot', text: t('scenario_dpfl_riemann_bot3'), timestamp: new Date().toISOString() },
            { id: '7', role: 'user', text: t('scenario_dpfl_riemann_user4'), timestamp: new Date().toISOString() },
            { id: '8', role: 'bot', text: t('scenario_dpfl_riemann_bot4'), timestamp: new Date().toISOString() },
            { id: '9', role: 'user', text: t('scenario_dpfl_riemann_user5'), timestamp: new Date().toISOString() },
            { id: '10', role: 'bot', text: t('scenario_dpfl_riemann_bot5'), timestamp: new Date().toISOString() },
            { id: '11', role: 'user', text: t('scenario_dpfl_riemann_user6'), timestamp: new Date().toISOString() },
            { id: '12', role: 'bot', text: t('scenario_dpfl_riemann_bot6'), timestamp: new Date().toISOString() },
            { id: '13', role: 'user', text: t('scenario_dpfl_riemann_user7'), timestamp: new Date().toISOString() },
            { id: '14', role: 'bot', text: t('scenario_dpfl_riemann_bot7'), timestamp: new Date().toISOString() },
            { id: '15', role: 'user', text: t('scenario_dpfl_riemann_user8'), timestamp: new Date().toISOString() },
            { id: '16', role: 'bot', text: t('scenario_dpfl_riemann_bot8'), timestamp: new Date().toISOString() },
            { id: '17', role: 'user', text: t('scenario_dpfl_riemann_user9'), timestamp: new Date().toISOString() },
            { id: '18', role: 'bot', text: t('scenario_dpfl_riemann_bot9'), timestamp: new Date().toISOString() },
            { id: '19', role: 'user', text: t('scenario_dpfl_riemann_user10'), timestamp: new Date().toISOString() },
            { id: '20', role: 'bot', text: t('scenario_dpfl_riemann_bot10'), timestamp: new Date().toISOString() },
            { id: '21', role: 'user', text: t('scenario_dpfl_riemann_user11'), timestamp: new Date().toISOString() },
            { id: '22', role: 'bot', text: t('scenario_dpfl_riemann_bot11'), timestamp: new Date().toISOString() },
        ],
    },
    {
        id: 'dpfl_ocean',
        name: '📊 ' + t('scenario_dpfl_ocean_name'),
        description: t('scenario_dpfl_ocean_desc'),
        bot: chloeBot,
        chatHistory: [
            { id: '1', role: 'user', text: t('scenario_dpfl_ocean_user1'), timestamp: new Date().toISOString() },
            { id: '2', role: 'bot', text: t('scenario_dpfl_ocean_bot1'), timestamp: new Date().toISOString() },
            { id: '3', role: 'user', text: t('scenario_dpfl_ocean_user2'), timestamp: new Date().toISOString() },
            { id: '4', role: 'bot', text: t('scenario_dpfl_ocean_bot2'), timestamp: new Date().toISOString() },
            { id: '5', role: 'user', text: t('scenario_dpfl_ocean_user3'), timestamp: new Date().toISOString() },
            { id: '6', role: 'bot', text: t('scenario_dpfl_ocean_bot3'), timestamp: new Date().toISOString() },
            { id: '7', role: 'user', text: t('scenario_dpfl_ocean_user4'), timestamp: new Date().toISOString() },
            { id: '8', role: 'bot', text: t('scenario_dpfl_ocean_bot4'), timestamp: new Date().toISOString() },
            { id: '9', role: 'user', text: t('scenario_dpfl_ocean_user5'), timestamp: new Date().toISOString() },
            { id: '10', role: 'bot', text: t('scenario_dpfl_ocean_bot5'), timestamp: new Date().toISOString() },
            { id: '11', role: 'user', text: t('scenario_dpfl_ocean_user6'), timestamp: new Date().toISOString() },
            { id: '12', role: 'bot', text: t('scenario_dpfl_ocean_bot6'), timestamp: new Date().toISOString() },
            { id: '13', role: 'user', text: t('scenario_dpfl_ocean_user7'), timestamp: new Date().toISOString() },
            { id: '14', role: 'bot', text: t('scenario_dpfl_ocean_bot7'), timestamp: new Date().toISOString() },
            { id: '15', role: 'user', text: t('scenario_dpfl_ocean_user8'), timestamp: new Date().toISOString() },
            { id: '16', role: 'bot', text: t('scenario_dpfl_ocean_bot8'), timestamp: new Date().toISOString() },
            { id: '17', role: 'user', text: t('scenario_dpfl_ocean_user9'), timestamp: new Date().toISOString() },
            { id: '18', role: 'bot', text: t('scenario_dpfl_ocean_bot9'), timestamp: new Date().toISOString() },
            { id: '19', role: 'user', text: t('scenario_dpfl_ocean_user10'), timestamp: new Date().toISOString() },
            { id: '20', role: 'bot', text: t('scenario_dpfl_ocean_bot10'), timestamp: new Date().toISOString() },
            { id: '21', role: 'user', text: t('scenario_dpfl_ocean_user11'), timestamp: new Date().toISOString() },
            { id: '22', role: 'bot', text: t('scenario_dpfl_ocean_bot11'), timestamp: new Date().toISOString() },
        ],
    },
    {
        id: 'dpc_blindspot',
        name: '🎯 ' + t('scenario_dpc_blindspot_name'),
        description: t('scenario_dpc_blindspot_desc'),
        bot: chloeBot,
        chatHistory: [
            { id: '1', role: 'user', text: t('scenario_dpc_blindspot_user1'), timestamp: new Date().toISOString() },
            { id: '2', role: 'bot', text: t('scenario_dpc_blindspot_bot1'), timestamp: new Date().toISOString() },
            { id: '3', role: 'user', text: t('scenario_dpc_blindspot_user2'), timestamp: new Date().toISOString() },
            { id: '4', role: 'bot', text: t('scenario_dpc_blindspot_bot2'), timestamp: new Date().toISOString() },
            { id: '5', role: 'user', text: t('scenario_dpc_blindspot_user3'), timestamp: new Date().toISOString() },
            { id: '6', role: 'bot', text: t('scenario_dpc_blindspot_bot3'), timestamp: new Date().toISOString() },
            { id: '7', role: 'user', text: t('scenario_dpc_blindspot_user4'), timestamp: new Date().toISOString() },
            { id: '8', role: 'bot', text: t('scenario_dpc_blindspot_bot4'), timestamp: new Date().toISOString() },
            { id: '9', role: 'user', text: t('scenario_dpc_blindspot_user5'), timestamp: new Date().toISOString() },
            { id: '10', role: 'bot', text: t('scenario_dpc_blindspot_bot5'), timestamp: new Date().toISOString() },
            { id: '11', role: 'user', text: t('scenario_dpc_blindspot_user6'), timestamp: new Date().toISOString() },
            { id: '12', role: 'bot', text: t('scenario_dpc_blindspot_bot6'), timestamp: new Date().toISOString() },
            { id: '13', role: 'user', text: t('scenario_dpc_blindspot_user7'), timestamp: new Date().toISOString() },
            { id: '14', role: 'bot', text: t('scenario_dpc_blindspot_bot7'), timestamp: new Date().toISOString() },
            { id: '15', role: 'user', text: t('scenario_dpc_blindspot_user8'), timestamp: new Date().toISOString() },
            { id: '16', role: 'bot', text: t('scenario_dpc_blindspot_bot8'), timestamp: new Date().toISOString() },
            { id: '17', role: 'user', text: t('scenario_dpc_blindspot_user9'), timestamp: new Date().toISOString() },
            { id: '18', role: 'bot', text: t('scenario_dpc_blindspot_bot9'), timestamp: new Date().toISOString() },
            { id: '19', role: 'user', text: t('scenario_dpc_blindspot_user10'), timestamp: new Date().toISOString() },
            { id: '20', role: 'bot', text: t('scenario_dpc_blindspot_bot10'), timestamp: new Date().toISOString() },
        ],
    },
];
